### ISSUE TITLE
Core Refactoring

### ISSUE THREAD

**Issue by madt1m** [marcomicera/followifier#75]
Core has all the ...core functionality working right now, but some functions are not isolated enough to make any change without modifying the entire server codebase. To make an example:

The function which computes the device position takes as argument an entire map of (board_mac:board_metadata), and extracts RSSI value from there.
This makes implementing #71 harder than it has to be, because in order to compute the position over an _average_ of positions I would have to proceed in two ways:

- Create a fake metadata with the average of RSSI (this is hacky and could probably break something else)
- Compute the average on positions instead of RSSI, and insert the average of positions into database. This route cannot be followed though, because for some reason the database object also accepts the entire ESP32 message in insert_message, so I cannot link an 'average of positions' to a given message, without again following hacky solutions.
 
I will proceed with a refactoring of the structures and functions in order to provide a bit more readability and modularity, so that we can implement new stuff on the server as fast as we can.

**Comment by marcomicera** [comment]
Outdated issue. Closing...
