### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by madt1m** [marcomicera/followifier#82]
Let's compile a list of possible - manual and not - tests to run on the system to assure that our assertions on its functionality are consistent.

- [ ] What happens when the NTP service suddenly stops?
- [ ] What happens if one board crashes (#61)?
- [ ] What happens if a board which is not listed in the server's `config.json` file sends a batch to the server?
- [ ] ...

**Comment by marcomicera** [comment]
Outdated issue. Closing...
